language: python
sudo: false
matrix:
    include:
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"

# setup adapted from https://github.com/bsmurphy/PyKrige/blob/master/.travis.yml
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda config --add channels conda-forge
    - conda update --yes conda
    - conda info -a

install:
    - conda create -q -n pycomlink-env python=${TRAVIS_PYTHON_VERSION} --file requirements.txt --channel conda-forge --yes
    - source activate pycomlink-env
    - conda install -c conda-forge --yes pip codecov
    #- pip install coveralls
    - pip install pytest pytest-cov
    - python -V
    #- python setup.py build_ext --inplace
    #- python setup.py install
    - python setup.py develop --no-deps
    - pwd
    - du -h

# command to run tests
script:
    - export NUMBA_DISABLE_JIT=1
    - py.test --cov

after_success:
    - codecov