name: pycomlink-dev
channels:
  - conda-forge
dependencies:
 - numpy
 - scipy
 - pandas
 - matplotlib
 - numba
 - h5py
 - xarray
 - sparse
 - netcdf4
 - shapely
 - pyproj
 - tqdm
 - pykrige
 - tensorflow
 - bottleneck
 - future
 - pip
 - pip:
   - git+https://github.com/pycomlink/pycomlink.git#egg=pycomlink
