name: pycomlink-dev
channels:
  - conda-forge
dependencies:
 - numpy
 - scipy
 - pandas>=0.22
 - matplotlib
 - numba
 - h5py
 - xarray
 - netcdf4
 - h5netcdf
 - shapely
 - pyproj
 - tqdm
 - pykrige
 - tensorflow
 - future
 - jupyterlab
 - notebook
 - bottleneck
 - pytest
